url: http://yoursite.com
title: Your Awesome Site
email: your-email@domain.com
author: Your Name
description: >
  Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# Jekyll & Plugins
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

# 3rd Party Settings
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 

# Additional Settings from second file
baseurl: "/zolan" # the subpath of your site, e.g. /blog
paginate: 5
paginate_path: "/page/:num"
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed