url: https://xiaobaiiiiii.github.io/
title: Chunge Bai's Homepage
email: bcg971004@icloud.com
author: Chunge Bai
description: >
  Welcome to Chunge Bai's Homepage! Discover insightful content and more.
copyright: 'Copyright &copy; 2024 Chunge Bai. All Rights Reserved.'
credits: 'Credits: This site uses a free, open source Bootstrap theme from <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# Jekyll & Plugins
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# 3rd Party Settings
social:
  - title: wechat
    url: 
  - title: github
    url: https://github.com/XiaoBaiiiiii
  - title: linkedin
    url: https://www.linkedin.com/in/chunge-bai-04991a309

# Additional Settings from second file
baseurl: "/projects" # the subpath of your site, e.g. /blog
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
include:
  - _pages

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed