#-------------------------------
# General Site Settings
title: Chunge Bai's Homepage
description: Chunge Bai's Personal Homepage


#-------------------------------
# Author Settings
author:
  name: Chunge Bai
  image: personal_pic.jpg
  image_location: Yokohama, Japan, 2024
  say-hello: Hello, I’m <strong>Chunge Bai</strong>. 
  bio: |
    I obtained my Master’s degree in Artificial Intelligence from Tsinghua University, specializing in SLAM, 3D reconstruction, and multi-sensor fusion. 
    Now I am working at Agibot as an Embodied Intelligence Algorithm Engineer, 
    where I have developed and maintained the company's complete SLAM system, encompassing mapping, localization, and re-localization. 
    I have developed several sensor fusion calibration algorithms.
    Now I am currently focusing on local obstacle avoidance ESDF mapping for robotic grasping. 
    My research interests include 
    <a href="#">3D/simulation reconstruction</a>, 
    <a href="#">3D rendering</a>, 
    <a href="#">augmented reality</a>, and 
    <a href="#">mixed reality</a>.


#-------------------------------
# Contact links
contact:
  github: https://github.com/XiaoBaiiiiii
  gmail: bcg971004@gmail.com
  telephone: +86 15545110569

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
